### ISSUE TITLE
Ema Calculation is not correct

### ISSUE THREAD

**Issue by softdev021** [brigb123/AutoCryp#6]
Talib library is producing different output for given period.  and talib library output is same as what mt4 IEMA function produces but this library IEMA is producing different values which are wrong as per comparison with talib and meta trader 4
https://github.com/brigb123/AutoCryp/blob/b62123df692daac32a7e9cacbd9eafe5b6f9cb27/MarketLib/MarketMath.cs

**Comment by brigb123** [comment]
Math is modeled from:
Initial SMA: 10-period sum / 10 

Multiplier: (2 / (Time periods + 1) ) = (2 / (10 + 1) ) = 0.1818 (18.18%)

EMA: {Close - EMA(previous day)} x multiplier + EMA(previous day). 

on webpage: 
https://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_averages

Are you using a different EMA model?
